Homework12: Anastasiya Solodukho
AnastasiyaSo/PythonTestProject pull request #10
Opened 2024-06-16 18:47 UTC by AnastasiyaSo

Added homework12

2024-06-21 19:01 UTC, Stml89 requested changes

2024-06-21 19:01 UTC, Stml89 commented on homework/homework12/homework12_1.py
> +        self.cards_list.append(Card("Joker", None))
```suggestion
        self.cards_list.append(Card("Joker", "Red"))
        self.cards_list.append(Card("Joker", "Black"))
```

2024-06-21 19:01 UTC, Stml89 commented on homework/homework12/homework12_1.py
> +            for n in deck_number_list:
```suggestion
        for i in Card.mast_list:
            for n in Card.number_list:
```

2024-06-21 19:01 UTC, Stml89 commented on homework/homework12/homework12_2.py
> +    def exchange_currency(self, currency_from, person_amount,
move it to the `currency` class

2024-06-22 07:25 UTC, AnastasiyaSo commented on homework/homework12/homework12_2.py
> +    def exchange_currency(self, currency_from, person_amount,
I don't understand why. In HW we should expand Banks methods

2024-06-25 17:15 UTC, AnastasiyaSo commented
@Stml89, I added deposit method from HW 11. Please, check

2024-06-27 19:52 UTC, Stml89 approved these changes

2024-07-01 18:02 UTC, merged