Homework14: Anastasiya Solodukho
AnastasiyaSo/PythonTestProject pull request #11
Opened 2024-06-21 16:26 UTC by AnastasiyaSo

2024-06-22 21:47 UTC, Stml89 requested changes

2024-06-22 21:47 UTC, Stml89 commented on homework/homework_14/homework_14_1.py
> +                                      "student6 group2 3\n")
Store information separately:
```suggestion
    students_data = [
        "Serena Williams","1A",[5,4,4,3],
        "Lionel Messi","2B",[4,3,5,2],
        "Kobe Bryant","1A",[3,5,4,1]
    ]
    ...
    with open("students.txt", "w+", encoding="utf-8") as students_file:
        students_file.write('\n'.join(students_data) + '\n')
```

2024-06-25 19:15 UTC, AnastasiyaSo commented
@Stml89, I fixed. Please, check

2024-06-28 20:31 UTC, Stml89 approved these changes

2024-07-01 18:02 UTC, merged