Homework20: Anastasiya Solodukho
AnastasiyaSo/PythonTestProject pull request #12
Opened 2024-07-16 15:43 UTC by AnastasiyaSo

Homework20 was added

2024-07-19 20:03 UTC, Stml89 requested changes

2024-07-19 20:03 UTC, Stml89 commented on homework/homework_11/homework_11_1.py
> +# assert client_1.return_book(book_1), True
if you do not want to execute code in case where module imported, just use:
`if __name__ == __main__`

2024-07-19 20:03 UTC, Stml89 commented on homework/homework_11/homework_11_2.py
> +# assert bank_1.method_deposit(deposit_1) == Decimal("1220.39")
the same

2024-07-19 20:03 UTC, Stml89 commented on homework/homework_20/homework_20_2.py
> +logger.setLevel(logging.INFO)
You can use 1 logger across an application, e.g.: https://stackoverflow.com/questions/75489656/how-to-use-a-single-python-logging-object-throughout-the-python-application

2024-07-26 10:52 UTC, AnastasiyaSo commented
@Stml89, hello. I fixed. Please, check

2024-07-27 16:48 UTC, Stml89 approved these changes

2024-07-29 08:33 UTC, merged