Homework21: Anastasiya Solodukho
AnastasiyaSo/PythonTestProject pull request #13
Opened 2024-07-19 09:08 UTC by AnastasiyaSo

Homework 21 was added

2024-07-20 19:58 UTC, Stml89 requested changes

2024-07-20 19:58 UTC, Stml89 commented on homework/homework_11/homework_11_1.py
> +# assert client_1.return_book(book_1), True
if you do not want to execute some code incase of module importing, just use "if __name__ == "__main__""

2024-07-20 19:58 UTC, Stml89 commented on homework/homework_11/homework_11_2.py
> +# assert bank_1.method_deposit(deposit_1) == Decimal("1220.39")
the same

2024-07-20 19:58 UTC, Stml89 commented on homework/homework_20/homework_20_1.py
> +logger.setLevel(logging.INFO)
You can use 1 logger across a single application, e.g.: https://stackoverflow.com/questions/75489656/how-to-use-a-single-python-logging-object-throughout-the-python-application

2024-07-20 19:58 UTC, Stml89 commented on homework/homework_20/homework_20_1.py
> +logger.setLevel(logging.INFO)
but you already have it in the `logger_module.py`, so it here as well

2024-07-29 08:47 UTC, AnastasiyaSo commented
@Stml89, I fixed. Please, check

2024-08-02 20:23 UTC, Stml89 requested changes

2024-08-02 20:23 UTC, Stml89 commented on .pylintrc
if I'm not mistaken, you have `pylint.yaml` file, so use it instead of this file

2024-08-02 20:23 UTC, Stml89 commented on report_21_1.html
Remove it from the repo, and add to `.gitignore`

2024-08-02 20:23 UTC, Stml89 commented on report_21_2.html
Remove it from the repo, and add to `.gitignore`

2024-08-02 20:23 UTC, Stml89 commented on homework/logger_module.py
Use `pytest.ini` instead of this file

2024-08-03 09:53 UTC, AnastasiyaSo commented on homework/logger_module.py
I don't have file pytest.ini and I don't know how to use the file. Why my logger module is incorrect?

2024-08-03 09:53 UTC, AnastasiyaSo commented on report_21_1.html
Done

2024-08-03 09:57 UTC, AnastasiyaSo commented on .pylintrc
![image](https://github.com/user-attachments/assets/0a4e327f-8f10-4123-978e-9960c56a47f5)
This solution does not work

2024-08-03 10:01 UTC, AnastasiyaSo commented
Hello! Please, see comments and PR

2024-08-04 13:34 UTC, Stml89 commented on homework/logger_module.py
I'm not saying it's wrong, but I see this file in the repository at the path `homework/homework_21/pytest.ini`. So I'm a bit confused.

2024-08-04 13:35 UTC, Stml89 commented on .pylintrc
yes, this file `pulint.yaml` is it a setup for GitHub actions, not for local run

2024-08-04 13:36 UTC, Stml89 commented
> Hello! Please, see comments and PR

Replied

2024-08-05 20:39 UTC, AnastasiyaSo commented on homework/logger_module.py
I decided to delete pytest.ini file :)

2024-08-10 06:59 UTC, Stml89 approved these changes

2024-08-10 10:38 UTC, merged