Homework10: Anastasiya Solodukho
AnastasiyaSo/PythonTestProject pull request #8
Opened 2024-06-04 20:01 UTC by AnastasiyaSo

Added HW10

2024-06-07 20:40 UTC, Stml89 requested changes

2024-06-07 20:40 UTC, Stml89 commented on homework_10.py
> +            raise ValueError
```suggestion
            if i < 0:
                raise ValueError(<error message>)
            ...

```

2024-06-07 20:40 UTC, Stml89 commented on homework_10.py
Please put each task into a separate file

2024-06-07 20:40 UTC, Stml89 commented on homework_10.py
> +        func(a, b)
```suggestion
        result = func(a, b)
```

2024-06-07 20:40 UTC, Stml89 commented on homework_10.py
> +                return _float
```suggestion
    converted_args = map(_type, args)
    func(converted_args)
```

2024-06-07 20:40 UTC, Stml89 commented on homework_10.py
> +    return arg
```suggestion
def add_str(a, b):
    """Function that passes an argument"""
    return a + b
```

2024-06-11 15:55 UTC, AnastasiyaSo commented
@Stml89 fixed. Please, check

2024-06-11 21:30 UTC, Stml89 requested changes

2024-06-11 21:30 UTC, Stml89 commented on homework_10_2.py
> +        return f"{result} is not a number"
Better to return a `bool` instead of `str`

2024-06-11 21:30 UTC, Stml89 commented on homework_10_1.py
> +        return True
```suggestion
        return func(*arg)
```

2024-06-11 21:30 UTC, Stml89 commented on homework_10_3.py
> +            sum_numbers = sum(converted_args)
This functionality should be done in `add_str`, `add_int` and etc

2024-06-12 20:50 UTC, AnastasiyaSo commented
@Stml89 fixed again. Please, check

2024-06-16 15:47 UTC, Stml89 approved these changes

2024-06-16 16:32 UTC, merged