Homework11: Anastasiya Solodukho
AnastasiyaSo/PythonTestProject pull request #9
Opened 2024-06-13 20:36 UTC by AnastasiyaSo

Added Homework # 11

2024-06-16 10:05 UTC, Stml89 requested changes

2024-06-16 10:05 UTC, Stml89 commented on homework_11_2.py
> +assert bank_1.method_deposit(deposit_1), True
if the user puts 1000 for 1 year, with 10% -> she will have ~1104.71 at the end

2024-06-16 10:05 UTC, Stml89 commented on homework_11_1.py
> +        self.reserved_by = ""
```suggestion
        self.reserved_by = None
```

2024-06-16 20:19 UTC, AnastasiyaSo commented
@Stml89, I fixed. Please, check.

2024-06-17 17:31 UTC, Stml89 approved these changes

2024-06-22 06:52 UTC, merged